appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Lgm1coNvib75IF8OeYikpXaAjaudMgMOqBFtTIP0B2kDOkgV0MUVWRj8XU/slkT+WL3COW55Hxrf9O3FD6DCxGbJPumTcLzQZC7Xa/P385uP/h52OCbk6N434/DdoXqW5NLlnZWHPzP5dYwv2wOrpIEOWTwCNAE2X6MoK8dxxZRojz2sDJENJc/T73h7EUKTe7+qRRxSdLa40VCTTCLIT/+l7US8cyE4+5kg3kJrD+N6h2EckOnQ3CWrYHWUSDymAdzGaIVEzSgPm7ITguTqXEZTy4+I8xtW4XFGgohZiEINuFbI6wnh+GQ3hfqVCfYoyLLJLPQRPpGzrcjj88KYFML4ZIWdXAH2UE3HYu2e+EJjbshI7Ugwb8SWTzj82IU5g6c8y7dpZCmvAxywY4HdlttCfqNluwPc6MIV7/culX2HacBsvf5WkG7loPBta/ylwoz9ZpYSsNV110+SYipct8/7V76ZdwykZ+mgcwS+hKzG6J3ePsnm7oEXd0TpsKE7/9HuXPUG0Ejn8epDDMUaJGSmyh2UPFJ7GdROxl/FG7hhEE4rIyL9LFjN8PZ6Iv922y5mcuzXhUwm9Src9Di98x0fNlcj6xzK+QhyC6p8Xq+UpeqVG1nrXTkwg0adhXrik8flaNy1wQYk0gy7X2GzXvf8Zs3muDhYj9lvR13k6I4=}
provider:
  win: azure
conda_forge_output_validation: true
